main:
  - name: Infos
    url: /#infos
    weight: 10
  - name: Programm
    url: https://pretalx.ffkbu.de/freifunktag-2024/schedule/
    weight: 15
  - name: Anmelden
    url: https://pretix.ffkbu.de/ffkbu/fftag/
    weight: 20
  - name: FAQ
    url: /#oft-gefragt-faq
    weight: 30
  - name: Code of Conduct
    pageRef: code-of-conduct
    weight: 50
footer:
  - name: Matrix
    url: https://matrix.to/#/#fftag24:systemli.org
    weight: 10
  - name: E-Mail
    url: mailto:freifunktag@ffkbu.de
    weight: 10
  - name: Impressum
    pageRef: impressum
    weight: 50
    params: { offset: true }
  - name: Datenschutz
    url: https://kbu.freifunk.net/datenschutz/
    weight: 50
    params: { offset: true }
